# Generated by Django 5.2.17 on 2026-09-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main heading displayed on the banner (e.g., "One Mission. Many Ways to Create Change.")', max_length=200, verbose_name='Banner Title')),
                ('subtitle', models.TextField(blank=True, help_text='Supporting text displayed below the title', verbose_name='Subtitle')),
                ('image', models.ImageField(blank=True, help_text='Recommended size: 1920x1080px. Leave blank to use default background.', null=True, upload_to='cms/banners/', verbose_name='Banner Image')),
                ('button_text', models.CharField(blank=True, default='Learn More', max_length=50, verbose_name='Button Text')),
                ('button_link', models.CharField(blank=True, default='#programs', help_text='URL or anchor link (e.g., #programs, /register/)', max_length=300, verbose_name='Button Link')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this banner from the public site', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'db_table': 'cms_banner',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Initiative Title')),
                ('description', models.TextField(help_text='Brief description of this program/initiative', verbose_name='Description')),
                ('image', models.ImageField(blank=True, help_text='Recommended size: 600x400px', null=True, upload_to='cms/initiatives/', verbose_name='Initiative Image')),
                ('tag', models.CharField(blank=True, help_text='Category tag (e.g., "In Schools", "Beyond Schools", "Youth Leadership")', max_length=50, verbose_name='Tag')),
                ('link', models.CharField(blank=True, default='#programs', help_text='URL or anchor for "Learn more" button', max_length=300, verbose_name='Link')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Initiative',
                'verbose_name_plural': 'Initiatives',
                'db_table': 'cms_initiative',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Description text (e.g., "Children Impacted Every Year")', max_length=100, verbose_name='Label')),
                ('value', models.CharField(help_text='Stat value as displayed (e.g., "30K+", "7,500+", "18+")', max_length=50, verbose_name='Value')),
                ('icon', models.CharField(blank=True, default='bi-graph-up-arrow', max_length=50, verbose_name='Bootstrap Icon Class')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
                'db_table': 'cms_statistic',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisionMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('vision', 'Vision'), ('mission', 'Mission')], max_length=10, verbose_name='Section Type')),
                ('title', models.CharField(help_text='Heading for this vision/mission item', max_length=200, verbose_name='Title')),
                ('content', models.TextField(help_text='Full text content for this section', verbose_name='Content')),
                ('icon', models.CharField(blank=True, default='bi-star-fill', help_text='Bootstrap icon class name (e.g., bi-eye-fill, bi-bullseye)', max_length=50, verbose_name='Bootstrap Icon Class')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vision / Mission Item',
                'verbose_name_plural': 'Vision / Mission Items',
                'db_table': 'cms_vision_mission',
                'ordering': ['section_type', 'order', '-created_at'],
            },
        ),
    ]
