# Generated by Django 5.2.17 on 2026-09-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_aboutevent_aboutmilestone_annualreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='A single core value (e.g., Integrity, Inclusivity, Empathy, Transparency)', max_length=255, verbose_name='Core Value')),
                ('description', models.TextField(blank=True, help_text='Brief explanation of how this value guides our work', verbose_name='Description')),
                ('icon', models.CharField(blank=True, default='bi-shield-check', help_text='Bootstrap icon class (e.g., bi-shield-check, bi-heart-fill, bi-gem)', max_length=50, verbose_name='Bootstrap Icon Class')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Core Value',
                'verbose_name_plural': 'Core Values',
                'db_table': 'core_values',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OurStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text="Detailed narrative describing the NGO's founding, journey, and community impact.", verbose_name='Story Content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Our Story',
                'verbose_name_plural': 'Our Story',
                'db_table': 'our_story',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the program (e.g., Free Educational Resources)', max_length=255, verbose_name='Program Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the program and key activities', null=True, verbose_name='Program Description')),
                ('icon', models.CharField(blank=True, default='bi-mortarboard-fill', max_length=50, verbose_name='Bootstrap Icon Class')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'db_table': 'programs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='teammember',
            name='image_url',
            field=models.CharField(blank=True, default='', help_text="URL or path to the team member's photo", max_length=255, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(max_length=255, verbose_name='Designation / Role'),
        ),
        migrations.AlterModelTable(
            name='teammember',
            table='team_members',
        ),
    ]
