# Generated by Django 5.2.17 on 2026-09-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_project_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image to represent this program focus area', null=True, upload_to='cms/programs/', verbose_name='Program Image'),
        ),
    ]
