# Generated by Django 5.2.17 on 2026-09-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_imagegallery_mediacoverage_pressrelease_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegallery',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Image Gallery', 'verbose_name_plural': 'Image Galleries'},
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='image_path',
            field=models.ImageField(max_length=2083, upload_to='cms/gallery/', verbose_name='Image Path'),
        ),
        migrations.AlterModelTable(
            name='pressrelease',
            table='press_release',
        ),
        migrations.AlterModelTable(
            name='video',
            table='video',
        ),
    ]
