# Generated by Django 5.2.17 on 2026-09-25 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_imagegallery_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('note', models.TextField(blank=True, help_text='Internal note from admin about this registration', verbose_name='Admin Note')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Registered At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='cms.volunteeropportunity', verbose_name='Opportunity')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Volunteer')),
            ],
            options={
                'verbose_name': 'Volunteer Registration',
                'verbose_name_plural': 'Volunteer Registrations',
                'db_table': 'volunteer_registration',
                'ordering': ['-registered_at'],
                'unique_together': {('volunteer', 'opportunity')},
            },
        ),
    ]
