# Generated by Django 5.2.17 on 2026-09-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('volunteer', 'Volunteer'), ('donor', 'Donor'), ('user', 'User')], default='user', max_length=255, verbose_name='Role'),
        ),
    ]
